
services:
  backend:
    build: ./backend
    container_name: contest-tracker-backend
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/contest-tracker
      - PORT=5000
      - NODE_ENV=production
      - SERVER_URL=http://localhost:5001
    depends_on:
      - mongo
    restart: always
    networks:
      - contest-network

  frontend:
    build: ./frontend
    container_name: contest-tracker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
    networks:
      - contest-network

  mongo:
    image: mongo:6
    container_name: contest-tracker-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - contest-network

volumes:
  mongo_data:

networks:
  contest-network:
